//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.ArtistInfoes = new HashSet<ArtistInfo>();
            this.Artworks = new HashSet<Artwork>();
        }
    
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public string ImageLink { get; set; }
        public short DisplayOrder { get; set; }
        public string Hash { get; set; }
    
        public virtual ICollection<ArtistInfo> ArtistInfoes { get; set; }
        public virtual ICollection<Artwork> Artworks { get; set; }
    }
}
