//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistInfo
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public int LanguageId { get; set; }
        public int ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Language Language { get; set; }
    }
}
