//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artwork
    {
        public Artwork()
        {
            this.ArtworkInfoes = new HashSet<ArtworkInfo>();
        }
    
        public int Id { get; set; }
        public string ThumbLink { get; set; }
        public bool IsSold { get; set; }
        public string ImageLink { get; set; }
        public int DisplayOrder { get; set; }
        public int ArtistId { get; set; }
    
        public virtual ICollection<ArtworkInfo> ArtworkInfoes { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
