//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtworkInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ArtworkId { get; set; }
        public int LanguageId { get; set; }
    
        public virtual Artwork Artwork { get; set; }
        public virtual Language Language { get; set; }
    }
}
