//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.AartistInfoes = new HashSet<ArtistInfo>();
            this.ArtworkInfoes = new HashSet<ArtworkInfo>();
            this.LabelInfoes = new HashSet<LabelInfo>();
            this.AnnouncementInfoes = new HashSet<AnnouncementInfo>();
        }
    
        public int Id { get; set; }
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string FlagImage { get; set; }
        public string Locale { get; set; }
    
        public virtual ICollection<ArtistInfo> AartistInfoes { get; set; }
        public virtual ICollection<ArtworkInfo> ArtworkInfoes { get; set; }
        public virtual ICollection<LabelInfo> LabelInfoes { get; set; }
        public virtual ICollection<AnnouncementInfo> AnnouncementInfoes { get; set; }
    }
}
