//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZlatoArt2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social
    {
        public int Id { get; set; }
        public string LrgImage { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public string MidImage { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
    }
}
